name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.8.0  # Updated to a version compatible with Node.js 20
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Sync repository to EC2
      run: |
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" ./ ubuntu@18.142.237.16:/home/ubuntu/jenkins

    - name: Install dependencies and restart app
      run: |
        ssh ubuntu@18.142.237.16 << 'EOF'
        cd /home/ubuntu/jenkins
        npm install
        pm2 restart 0
        EOF

